---
title: "Certamen1_Diabetes"
author: "Diego Yáñez"
date: "03-05-2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("NbClust")
install.packages("cluster")
install.packages("ggplot2")
install.packages("dbscan")
install.packages("pca3d")
install.packages("psych")
install.packages("skimr")
install.packages("tidyverse")
install.packages("FactoMineR")
install.packages("magrittr")
install.packages("readxl")
install.packages("corrplot")
install.packages("DataExplorer")
install.packages("readr")
install.packages("DMwR2")
install.packages("FinCal")
install.packages("VIM")
install.packages("FSelectorRcpp")
install.packages("arules")
install.packages("entropy")
install.packages("xlsx")
install.packages("WriteXLS")
install.packages("GGally")
install.packages("Gifi")
install.packages("CompareGroups")
install.packages("NbClust")
install.packages("fpc")


library(cluster)
library(ggplot2)
library(fpc)
library(dbscan)
library(pca3d)
library(psych)
library(tidyverse)
library(FactoMineR)
library(factoextra)
library(magrittr)
library(readxl) 
library(skimr)
library(corrplot)
library(DataExplorer)
library(readr)
library(DMwR2)
library(FinCal)
library(VIM)
library(FSelectorRcpp)
library(arules)
library(entropy)
library(xlsx)
library(WriteXLS)
library(GGally)
library(Gifi)
library(compareGroups)
library(NbClust)
```

```{r }
diabetes<-read.csv2("diabetes.csv",sep = ",",na.strings=c("Unknown/Invalid","?","None"))
diabetes$diabetesMed<-NULL
diabetes_sin_tratar<-read.csv2("diabetes.csv",sep = ",",na.strings=c("Unknown/Invalid","?","None") )
diabetes <- diabetes[!duplicated(diabetes$patient_nbr), ]
diabetes_sin_tratar <- diabetes_sin_tratar[!duplicated(diabetes_sin_tratar$patient_nbr), ]

data_original <- read.csv2("diabetes.csv",sep = ",",na.strings=c("Unknown/Invalid","?","None") )
view(data_original)
rownames(diabetes)<-diabetes$patient_nbr
rownames(diabetes_sin_tratar)<-diabetes_sin_tratar$patient_nbr
diabetes<-diabetes[,c(-1,-2)]
View(diabetes)

```

```{r }
#Cambiar variables caracteres a factores
for (i in 1:ncol(diabetes)) {
  if (is.character(diabetes[[i]])==TRUE) {
    diabetes[[i]]<-as.factor(diabetes[[i]])
  }
}
```

```{r }
# Las variables 5 a 7 que corresponden a ID's de gravedad de admision, derivacion a otro lugar o fuente de admision se cambiaran a factores.
for (i in 5:7) {
  diabetes[[i]]<-as.factor(diabetes[[i]])
}
summary(diabetes)
```

```{r }
# Las id's anteriores, poseen datos NULL los cuales serán cambiados por NA
diabetes$admission_type_id[diabetes$admission_type_id == 6 ] <- NA
diabetes$admission_source_id[diabetes$admission_source_id == 17 ] <- NA
diabetes$discharge_disposition_id[diabetes$discharge_disposition_id == 18] <- NA
```

```{r }
#Eliminacion de columnas que poseen muchos NA.
i_col_na<-c() #definimos una variable que almacenará el indice i de la columna a eliminar.

for (i in 1:ncol(diabetes)) {
   sumacol <- sum(is.na(diabetes[,i]))
  cat("la suma de NA de la columna",i,"es",sumacol," y representa ",round(sumacol/nrow(diabetes)*100,2) ,"% del total de datos de la columna",i, "\n")
          if ( (round(sumacol/nrow(diabetes)*100,2))>= 30 ) {
            i_col_na  <-c(i_col_na , i )
          }
}
diabetes<-diabetes[,c(-i_col_na)] #eliminamos las columnas identificadas con más del 30% de NA.
```


```{r }
#Identificamos outliers y etiquetamos como NA

sum(is.na(diabetes)) #hasta este entonces existen 15492 NA

for (i in 1:ncol(diabetes)) {
  if ( is.numeric(diabetes[[i]])  ) {
     bplot <- boxplot(diabetes[[i]])
   diabetes[[i]][ diabetes[[i]] %in% bplot$out ] <- NA 
   bplot <- NA
  }
}
for (i in 1:ncol(diabetes)) {
  if ( is.numeric(diabetes[[i]])  ) {
     bplot <- boxplot(diabetes[[i]])
   diabetes[[i]][ diabetes[[i]] %in% bplot$out ] <- NA 
   bplot <- NA
  }
}
for (i in 1:ncol(diabetes)) {
  if ( is.numeric(diabetes[[i]])  ) {
     bplot <- boxplot(diabetes[[i]])
   diabetes[[i]][ diabetes[[i]] %in% bplot$out ] <- NA 
   bplot <- NA
  }
}

sum(is.na(diabetes)) #luego de etiquetar como NA los outliers, se tiene un total de 47053
#Ejecutando 3 veces el codigo anterior, se eliminarán todos los outliers.

```


```{r }
#Para variables numericas
#Se eliminaran variables con desviacion estandar muy cercana a 0.

i_col_sd<-c() #definimos una variable que almacenará el indice i de la columna a eliminar.
for (i in 1:ncol(diabetes)) {
  if (is.numeric(diabetes[[i]])) {
    cat("la desviacion estandar de la columna ",i," es ",sd(diabetes[[i]],na.rm = T), "\n")
  if ( sd(diabetes[[i]],na.rm = T) <= 0.1 ) {
            i_col_sd  <-c(i_col_sd , i )
          }
  }
}

diabetes<-diabetes[,c(-i_col_sd)] #en este caso, se elimina number_outpatient, number_emergency y number_inpatient


#Se eliminaran variables con coeficiente de variacion < 30.
i_col_cv<-c() #definimos una variable que almacenará el indice i de la columna a eliminar.

for (i in 1:ncol(diabetes)) {
  if (is.numeric(diabetes[[i]])) {
    cat("el coeficiente de variacion de la columna  ",i," es ",sd(diabetes[[i]],na.rm = T)/ mean(diabetes[[i]],na.rm = T), "\n")
     if (sd(diabetes[[i]] , na.rm = T)/ mean(diabetes[[i]],na.rm = T) <= 0.3) {
       i_col_cv <- c(i_col_cv ,i)
      }
   }
}
# El coeficiente de variacion arroja que la columna number_diagnoses presenta un coeficiente de variacion bajo (cercano al 30%), pero dado que las variables diag1, diag2 y diag3 se eliminarán, no se eliminará number_diagnoses bajo este criterio.

# diabetes<-diabetes[,c(-i_col_cv)] 

```

```{r }
#Para variables categoricas
i_entropy<-c() #definimos una variable que almacenará el indice i de la columna a eliminar.

  for (i in 1:ncol(diabetes)) {
  if (is.factor(diabetes[[i]]) ) {
     probabilities <- prop.table(table(diabetes[[i]]))
    cat("la entropia de la columna ",i," es ",entropy.empirical(probabilities, unit = "log2"), "\n")
    if (entropy.empirical(probabilities, unit = "log2") <=0.7 ) {
      i_entropy<-c(i_entropy,i)
    }
  }
  }

diabetes<-diabetes[,c(-i_entropy)] #Se eliminan 21 columnas categoricas del df diabetes.
```

```{r}
for (i in 1:10 ) {
    if(is.factor(diabetes[[i]])){
      probabilities <- prop.table(table(diabetes[[i]]))
      cat("la probabilidad de la columna ",i," es ", probabilities, "\n")
    }
}

```

```{r}
for (i in 14:18 ) {
    if(is.factor(diabetes[[i]])){
      probabilities <- prop.table(table(diabetes[[i]]))
      cat("la probabilidad de la columna ",i," es ", probabilities, "\n")
    }
}

# prop.table(table(diabetes$race))

summary(diabetes)
#la columna 1, 5, 15 y 18 poseen categorias con probabilities mayores a 60%, por lo que se eliminarán estas columnas.

probabilidades0.6<-c(1,5,15,18)
diabetes <- diabetes[ ,-(probabilidades0.6)]
```




```{r }
#Imputacion por knn. 
sum(is.na(diabetes)) #Se imputara un total de 19680 datos, luego de realizar la limpieza.

# diabetes <- kNN(diabetes,k=10)

sum(is.na(diabetes))

#Exportar de r a excel
# write.csv(diabetes,"diabetes_impute.csv")
```

```{r }
diabetes_impute<-read.csv2("diabetes_impute.csv",sep = ",",na.strings="?" )
diabetes_impute$X<-NULL
rownames(diabetes_impute)<- diabetes_sin_tratar$patient_nbr
view(diabetes_impute)

i_impute<-c() #definimos un vector que nos devuelva la columna creada por kNN que indica cuales registros fueron imputados.
for (i in ( (ncol(diabetes_impute)/2) + 1): ncol(diabetes_impute)) {
  i_impute<-c(i_impute,i)
}

true_false_col_impute <- diabetes_impute[ , i_impute]
diabetes_impute <- diabetes_impute[,-i_impute]
# write.csv(diabetes_impute,"diabetes_impute_2.csv") #guardamos base de datos diabetes lista para operar
```


```{r}
#df mixto
df_mixto<-read.csv2("diabetes_impute_2.csv",sep = ",",na.strings="?" )
rownames(df_mixto)<- df_mixto$X
df_mixto$X<-NULL

for (i in 1:ncol(df_mixto)) {
  if (is.character(df_mixto[[i]])==TRUE) {
    df_mixto[[i]]<-as.factor(df_mixto[[i]])
  }
}

#Cambiar variables a factor
for (i in 3:4) {
    df_mixto[[i]]<-as.factor(df_mixto[[i]])
}
```


```{r }
#df numerico
df<-read.csv2("diabetes_impute_2.csv",sep = ",",na.strings="?" ) 
rownames(df)<- df$X
df$X<-NULL

#Para poder hacer la matriz de correlaciones y luego el ACP, dejaremos solo las variables numericas
df$gender<- NULL
df$admission_type_id<-NULL
df$admission_source_id<-NULL
df$diag_1<- NULL
df$diag_2<-NULL
df$diag_3<-NULL
df$change<-NULL
df$age<-NULL
df$insulin<-NULL

# write.csv(df,"diabetes_listo.csv")
df<-read.csv2("diabetes_listo.csv",sep = ",",na.strings="?" )
rownames(df)<- df$X
df$X<-NULL


for (i in 1:ncol(df)) {
  df[[i]]<-as.numeric(df[[i]])
}
```

```{r }
# MATRIZ DE CORRELACIONES
df <- scale(df) #escalamos la base de datos debido a que no tienen las mismas unidades de medida
df <- as.data.frame(df)

MC<-df %>% cor() %>% round(.,2)
corrplot(MC)
correlaciones<-(as.data.frame(MC))
view(correlaciones)
```

```{r }
TT<-cortest.bartlett(MC)
cat("Se puede realizar el ACP debido a que el valor p = ",TT$p.value," es inferior a alfa=0.05, por lo tanto se rechaza la hipotesis H0 del test de bartlett, esto es, existe correlacion suficiente entre las variables",colnames(df))
```
```{r }
#ACP
ACP <- PCA(df,graph= TRUE) #ACP  2 D
 fviz_eig(ACP,addlabels = TRUE) #ACP

indices2 <- sample( 1:nrow( df ), 25,replace = F) #PARA ACP 3D
muestra_df<-df[indices2,]

ACP2<-prcomp(muestra_df) 
pca3d(ACP2, biplot=TRUE, show.plane=FALSE,show.labels = FALSE, axes.color = "blue",radius=1)
```

```{r }
#Representacion de las variables
var <- get_pca_var(ACP)
corrplot(var$cos2,is.corr = F) #Variables v/s Dimensión

fviz_pca_var(ACP,col.var="cos2",gradient.cols=c("#E74422","#DCD01D","#0440FF"),repel=TRUE)

rank_var<-ACP$var$cos2
rank_var<-as.data.frame(rank_var)
rank_var$Representacion<-(rank_var$Dim.1+rank_var$Dim.2+rank_var$Dim.3)*100
rank_var<-rank_var[,c(-4,-5)]
rank_var$Bien_o_Mal <- NA
rank_var$Bien_o_Mal[rank_var$Representacion>=60] <- "BIEN"
rank_var$Bien_o_Mal[rank_var$Representacion<=60] <- "MAL"

ranking_variable<- arrange(rank_var,desc(rank_var$Representacion))
# rank_var<-arrange(rank_var,desc(rank_var$Representacion))
view(rank_var)
view(ranking_variable)
```

```{r }
#Representacion de los individuos 
ind<-get_pca_ind(ACP)

fviz_pca_ind(ACP,col.ind="cos2",pointsize="cos2",gradient.cols=c("#E74422","#DCD01D","#0440FF"),repel=TRUE)
rank_ind<-ACP$ind$cos2
rank_ind<-as.data.frame(rank_ind)
rank_ind$Representacion<-(rank_ind$Dim.1+rank_ind$Dim.2+rank_ind$Dim.3)*100
rank_ind<-rank_ind[,c(-4,-5)]
rank_ind$Bien_o_Mal <- NA
rank_ind$Bien_o_Mal[rank_ind$Representacion>=60] <- "BIEN"
rank_ind$Bien_o_Mal[rank_ind$Representacion<=60] <- "MAL"

ranking_individuos <- arrange(rank_ind,desc(rank_ind$Representacion))
mejores5<-c(1,2,3,4,5)
peores5<-c(nrow(rank_ind)-10,nrow(rank_ind)-9,nrow(rank_ind)-8,nrow(rank_ind)-7,nrow(rank_ind)-6,nrow(rank_ind)-5)

#Ranking de los mejores y peores 5 individuos representados en ACP con 3 componentes.
ranking_individuos <- ranking_individuos[c(mejores5,peores5),]
view(ranking_individuos)
```

```{r }
#SOLO PARA GRAFICAR UNA MUESTRA DE 200 INDIVIDUOS BIEN/MAL REPRESENTADOS USANDO 3 COMPONENTES.
indices3 <- sample( 1:nrow( df ), 200,replace = F) #PARA CAPTURAR INDICES DE LA MUESTRA
muestra_df2<-df[indices3,]


ACP3<- PCA(muestra_df2,graph=TRUE)

ind2<-get_pca_ind(ACP3)
rank_ind2<-ACP3$ind$cos2
rank_ind2<-as.data.frame(rank_ind2)
rank_ind2$Representacion<-(rank_ind2$Dim.1+rank_ind2$Dim.2+rank_ind2$Dim.3)*100
rank_ind2<-rank_ind2[,c(-4,-5)]
rank_ind2$Bien_o_Mal <- NA
rank_ind2$Bien_o_Mal[rank_ind2$Representacion>=60] <- "BIEN"
rank_ind2$Bien_o_Mal[rank_ind2$Representacion<=60] <- "MAL"
view(rank_ind2)

  grupo<-as.factor(rank_ind2$Bien_o_Mal)
fviz_pca_biplot(ACP3,col.ind=grupo,palette = c("#00AFBB","#FC4E07","696969"),addEllipses = TRUE)
```

```{r}
#Representación de los 100 individuos que más contribuyen al ACP en 2d
fviz_pca_biplot(ACP,repel=TRUE, col.var = "#2E9FDF",col.ind = "#696969", select.ind=list(contrib=100))
```



```{r}
#BORRAR DIMENSIONES E INDIVIDUOS MAL REPRESENTADOS
#INDIVIDUOS
columnas<-c(1,2,3,4,5)
columnas_sin_tratar<-c(1:50)


for (i in 1:ncol(diabetes_sin_tratar)) {
  diabetes_sin_tratar[[i]]<-as.character(diabetes_sin_tratar[[i]])
}




for (i in 1:nrow(df)) {
  if (rank_ind[i,4] < 60) {
    df[i,columnas]<- NA
    df_mixto[i,columnas]<- NA
    diabetes_sin_tratar[i,51]<-"eliminar"
  }
}

for (i in 1:nrow(df)) {
  if(is.na(diabetes_sin_tratar[i,51])){
    diabetes_sin_tratar[i,51]="no eliminar"
  }
}

diabetes_sin_tratar<- diabetes_sin_tratar[!(diabetes_sin_tratar$V51 =="eliminar"),]


df<-as.data.frame(df)
df<-na.omit(df)
df_mixto<-na.omit(df_mixto)

view(rank_ind)
view(df)
view(df_mixto)
view(diabetes_sin_tratar)


view(rank_ind)

```

```{r}
#EXTRACTO DE MUESTRA 100 INDIVIDUOS
indices100 <- sample( 1:nrow( df ), 100,replace = F)
muestra100_num<-df[indices100,]
muestra100_mixto<-df_mixto[indices100,]
muestra_sin_tratar<-diabetes_sin_tratar[indices100,]



view(muestra100_num)
view(muestra100_mixto)
view(muestra_sin_tratar)
```



```{r}
#SELECCION NUMERO OPTIMO DE CLUSTERS
fviz_nbclust(x = muestra100_num, FUNcluster = kmeans, method = "wss", k.max = 25) +
  labs(title = "Numero Optimo de clusters") #Seleccion de número óptimo de clusters: 5

MD<-muestra100_num %>% dist(.,method = "euclidean") %>% as.matrix()
heatmap(MD) #Apoyandose en el mapa de calor, se puede confirmar la selección de 5 clusters.

#CREACION DE TABLAS QUE MUESTRE LOS CLUSTERS
tabla_clara <- muestra100_mixto
tabla_kmean <- muestra100_num
tabla_clustermixto<-muestra100_mixto
```


```{r}
#metodo ward - jerarquico
hc<-muestra100_num  %>% dist(method ="euclidean") %>% hclust(method = "ward.D")
fviz_dend(x=hc, k=5,cex = 0.8) + geom_hline(yintercept = 8.7,linetype = "dashed")

set.seed(2020)
 fviz_dend(x = hc,
          k = 5,
          k_colors = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07","696969"),
          color_labels_by_k = TRUE,
          cex = 0.8,
          type = "phylogenic",
          repel = TRUE)

 
```



```{r}
#k mean - no jerarquico
set.seed(321)
km_clusters<-kmeans(x=muestra100_num, centers=5,nstart=10)

#grafico
fviz_cluster(object=km_clusters,data=muestra100_num,pointsize=2,geom="point",ellipse = T, show.clust.cent = TRUE, pallete="jco")+
  theme_bw()+theme(legend.position = "none")
#grafico
fviz_cluster(km_clusters,data=muestra100_num,ellipse.type = "euclid",repel=TRUE,star.plot=TRUE)

#grafico
fviz_cluster(km_clusters, data = muestra100_num,repel=TRUE)

#ASIGNACION DE CLUSTER 
tabla_kmean$cluster_kmean<-km_clusters$cluster
group1<-compareGroups(cluster_kmean~.,data=tabla_kmean)
clustab1<-createTable(group1)
view(data_original)
```



```{r}
#Cluster Mixto
cluster_mixto<-daisy(muestra100_mixto,metric="gower")
round(as.matrix(cluster_mixto),2)
heatmap(as.matrix(cluster_mixto))


#grafico
distancias<-as.dist(cluster_mixto)
fviz_dist(distancias)

mixedClusters<-kmeans(cluster_mixto, centers=5)



#ASIGNACION DE CLUSTER 
tabla_clustermixto$cluster_mixto<-mixedClusters$cluster
group2<-compareGroups(cluster_mixto~.,data=tabla_clustermixto)
clustab2<-createTable(group2)

# write.csv(muestra1000,"mixto.csv")
```

```{r}
#cluster clara 
clara_clusters <- clara(x = muestra100_mixto, k = 5, metric = "manhattan", stand = TRUE, pamLike = TRUE)


#grafico
clara_clusters
fviz_cluster(object = clara_clusters, ellipse.type = "t", geom = "point",
             pointsize = 2.5) +
  theme_bw() +
  labs(title = "Resultados clustering CLARA") +
  theme(legend.position = "none")

#grafico
fviz_cluster(clara_clusters,data=muestra100_mixto,ellipse.type = "euclid",repel=TRUE,star.plot=TRUE)

#grafico
fviz_cluster(clara_clusters, data = muestra100_mixto,repel=TRUE)


#ASIGNACION DE CLUSTER 
tabla_clara$cluster_clara<-clara_clusters$clustering
group3<-compareGroups(cluster_clara~.,data=tabla_clara)
clustab3<-createTable(group3)
```
```{r}
#V/S ASIGNACIONES DE CLUSTERS

clustering<-muestra100_mixto
clustering$cluster_kmean<-tabla_kmean$cluster_kmean
clustering$cluster_mixto<- tabla_clustermixto$cluster_mixto
clustering$cluster_clara <- tabla_clara$cluster_clara
clustering$diabetes_med <- muestra_sin_tratar$diabetesMed

view(muestra_sin_tratar)
view(muestra100_mixto)

clustering<-clustering[,c(15,16,17,18)]
view(clustering)
```


```{r}
#COINCIDENCIAS CLUSTERS
ACP4<- PCA(muestra100_num,graph=TRUE)
kmean_grupo<-as.factor(clustering$cluster_kmean)
clara_grupo<-as.factor(clustering$cluster_clara)
mixto_grupo<-as.factor(clustering$cluster_mixto)

fviz_pca_biplot(ACP4,col.ind=kmean_grupo,palette = c("#00AFBB","#FC4E07","696969","#85A0AB","#F72FDC"),repel=TRUE,select.ind=list(contrib=20),title = "Agrupacion 20 individuos mejor representados - Cluster KMEAN") 
fviz_pca_biplot(ACP4,col.ind=clara_grupo,palette = c("#00AFBB","#FC4E07","696969","#85A0AB","#F72FDC"),repel=TRUE,select.ind=list(contrib=20),title = "Agrupacion 20 individuos mejor representados - Cluster Clara")
fviz_pca_biplot(ACP4,col.ind=mixto_grupo,palette = c("#00AFBB","#FC4E07","696969","#85A0AB","#F72FDC"),repel=TRUE,select.ind=list(contrib=20),title = "Agrupacion 20 individuos mejor representados - Cluster Mixto")

#Resultado - Resumen de TABLAS DE ASIGNACION
resultado<-clustering[,c(15,16,17,18)]
for (i in 1:ncol(resultado)) {
 resultado[[i]]<-as.factor(resultado[[i]])
}
summary(resultado)
group_label<-compareGroups(diabetes_med~.,data=resultado)
clustab_resultado<-createTable(group_label)
```
```{r}
#MEJOR CLUSTER - CLUSTER MIXTO y CLARA.
clustab2 #mixto
clustab3 #clara
 
```
```{r}
#VALIDACION

validacion <- filter(data_original, age %in% c("[40-50)","[50-60)","[60-70)","[70-80)","[80-90)","[90-100)"), admission_type_id %in% c(1,2,3), admission_source_id %in% c(1,2), time_in_hospital >= 4, num_lab_procedures >= 49, insulin %in% c("Steady","Up"), change %in% "Ch")

summary(validacion)

validacion_limpia <- validacion[,c(5,7,9,10,13,42,48,49)]
# view(validacion_limpia)

diabetes_contador<-0
for (i in 1:nrow(validacion_limpia)) {
  if(validacion_limpia[i,8]=="Yes"){
    diabetes_contador <- diabetes_contador + 1
  }
}
cat("El porcentaje de acierto del cluster 2 del metodo kmean es",diabetes_contador/nrow(validacion_kmean)*100,"%")

#Se puede apreciar que el patron descrito describe muy bien a los individuos que son diagnosticados de diabetes.



validacion_kmean <- filter(data_original, time_in_hospital >= 1, num_lab_procedures >= 1, num_procedures >= 1, number_diagnoses >= 1, num_medications >= 1)

contador_validacion<-0
for (i in 1:nrow(validacion_kmean)) {
  if (validacion_kmean[i,49]=="Yes") {
    contador_validacion<-contador_validacion+1
  }
}
cat("El porcentaje de acierto del cluster 2 del metodo kmean es",contador_validacion/nrow(validacion_kmean)*100,"%")


```


















